# fly.toml app configuration file generated for humanhelp on 2023-07-31T09:50:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "humanhelp"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
